---
# Config
baseurl: "https://budgie-desktop.org/"
config: "config.yaml"
title: "Budgie Desktop"
# Content
archetypedir: "themes/budgie/archetypes"
buildDrafts: false
googleanalytics: "UA-Not-Yet"
languageCode: "en-us"
metaDataFormat: "yaml"
paginate: 5
layoutsdir:   "themes/budgie/layouts"
# Blackfriday Markdown Tweaks
blackfriday:
    hrefTargetBlank: true # Opens external URLs in a new tab / window (target _blank)
# Menu
menu:
  header:
      - Name: "Home"
        Identifier: "home"
        URL: "/home"
        Weight: 1
      - Name: "About"
        Identifier: "about"
        URL: "/about"
        Weight: 2
      - Name: "Blog"
        Identifier: "blog"
        URL: "/blog"
        Weight: 3
      - Name: "Get"
        Identifier: "get"
        URL: "/get"
        Weight: 4
      - Name: "Roadmap"
        Identifier: "roadmap"
        URL: "/roadmap"
        Weight: 5
      - Name: "Showcase"
        Identifier: "showcase"
        URL: "/showcase"
        Weight: 6
# Special Params
params:
    budgieversion: "10.3.1"
    category: ["development"]
    copyright: "2017"
# Theming
themesDir: "themes"
theme: "budgie"
---